server.port=8084
spring.datasource.url=jdbc:h2:mem:store
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
resilience4j.circuitbreaker.instances.productoServiceCB.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.productoServiceCB.slidingWindowSize=10
resilience4j.circuitbreaker.instances.productoServiceCB.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.productoServiceCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.productoServiceCB.waitDurationInOpenState=1m
resilience4j.circuitbreaker.instances.productoServiceCB.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.productoServiceCB.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.productoServiceCB.maxWaitDurationInHalfOpenState=20s
resilience4j.timelimiter.instances.productoServiceCB.timeoutDuration=3s
